modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Apollounknowndev/lithostitched/issues"
license = "MIT"

[[mods]]
    modId = "lithostitched"
    version = "${file.jarVersion}"
    displayName = "Lithostitched"
    logoFile = "pack.png"
    authors = "Apollo, SmellyModder"
    description = '''Library mod with new configurability and compatibility enhancements for worldgen.'''

[[mixins]]
config = "lithostitched.mixins.json"

[[mixins]]
config = "lithostitched.neoforge.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies.lithostitched]]
    modId = "neoforge"
    type = "required"
    versionRange = "[20.5,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.lithostitched]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.20.5,1.21)"
    ordering = "NONE"
    side = "BOTH"
